name: my_flutter_app
description: A new Flutter project
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  file_picker: ^10.3.3
  flutter_colorpicker: ^1.1.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^3.1.0
  go_router: ^16.2.4
  google_fonts: ^6.3.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  table_calendar: ^3.2.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
